apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: ovn
spec:
  label: dataplane-deployment-ovn
  playbook: osp.edpm.ovn
  configMaps:
  - ovncontroller-config
