apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dataplane-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OpenStackDataPlaneNode is the Schema for the openstackdataplanenodes
        API
      displayName: OpenStack Data Plane Node
      kind: OpenStackDataPlaneNode
      name: openstackdataplanenodes.dataplane.openstack.org
      specDescriptors:
      - description: Deploy boolean to trigger ansible execution
        displayName: Deploy
        path: deployStrategy.deploy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: AnsiblePort SSH port for Ansible connection
        displayName: Ansible Port
        path: node.ansiblePort
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: 'AnsibleSSHPrivateKeySecret Private SSH Key secret containing
          private SSH key for connecting to node. Must be of the form: Secret.data.ssh-privatekey:
          <base64 encoded private key contents> https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets'
        displayName: Ansible SSHPrivate Key Secret
        path: node.ansibleSSHPrivateKeySecret
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: Managed - Whether the node is actually provisioned (True) or
          should be treated as preprovisioned (False)
        displayName: Managed
        path: node.managed
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors:
      - description: Conditions
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      - description: Deployed
        displayName: Deployed
        path: deployed
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      version: v1beta1
    - description: OpenStackDataPlaneRole is the Schema for the openstackdataplaneroles
        API
      displayName: OpenStack Data Plane Role
      kind: OpenStackDataPlaneRole
      name: openstackdataplaneroles.dataplane.openstack.org
      specDescriptors:
      - description: Deploy boolean to trigger ansible execution
        displayName: Deploy
        path: deployStrategy.deploy
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: AnsiblePort SSH port for Ansible connection
        displayName: Ansible Port
        path: nodeTemplate.ansiblePort
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: 'AnsibleSSHPrivateKeySecret Private SSH Key secret containing
          private SSH key for connecting to node. Must be of the form: Secret.data.ssh-privatekey:
          <base64 encoded private key contents> https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets'
        displayName: Ansible SSHPrivate Key Secret
        path: nodeTemplate.ansibleSSHPrivateKeySecret
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: Managed - Whether the node is actually provisioned (True) or
          should be treated as preprovisioned (False)
        displayName: Managed
        path: nodeTemplate.managed
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors:
      - description: Conditions
        displayName: Conditions
        path: conditions
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      - description: Deployed
        displayName: Deployed
        path: deployed
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      version: v1beta1
  description: The OpenStack DataPlane Operator
  displayName: OpenStack DataPlane Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openstack
  - dataplane
  links:
  - name: Dataplane Operator
    url: https://openstack-k8s-operators.github.io/dataplane-operator
  maintainers:
  - email: rhos-upgrades@redhat.com
    name: RHOS Uprades
  maturity: alpha
  provider:
    name: rhosp
  version: 0.0.0
