apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: edpm-compute-0
spec:
  role: edpm-compute
  hostName: edpm-compute-0
  ansibleHost: 192.168.122.100
  node:
    ansibleVars: |
      tenant_ip: 192.168.24.100
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
  deployStrategy:
    deploy: false
