apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-ceph
  namespace: openstack
spec:
  env:
  - name: ANSIBLE_CALLBACKS_ENABLED
    value: profile_tasks
  - name: ANSIBLE_FORCE_COLOR
    value: "True"
  - name: ANSIBLE_ENABLE_TASK_DEBUGGER
    value: "True"
  networkAttachments:
  - ctlplane
  nodeTemplate:
    ansible:
      ansiblePort: 22
      ansibleUser: cloud-admin
      ansibleVars:
        ctlplane_dns_nameservers:
        - 192.168.122.1
        ctlplane_gateway_ip: 192.168.122.1
        ctlplane_host_routes:
        - ip_netmask: 0.0.0.0/0
          next_hop: 192.168.122.1
        ctlplane_mtu: 1500
        ctlplane_subnet_cidr: 24
        dns_search_domains: []
        timesync_ntp_servers:
        - hostname: pool.ntp.org
        edpm_iscsid_image: '{{ registry_url }}/{{ image_prefix }}-iscsid:{{ image_tag }}'
        edpm_logrotate_crond_image: '{{ registry_url }}/{{ image_prefix }}-cron:{{ image_tag
          }}'
        edpm_network_config_hide_sensitive_logs: false
        edpm_network_config_template: |
          ---
          {% set mtu_list = [ctlplane_mtu] %}
          {% for network in role_networks %}
          {{ mtu_list.append(lookup('vars', networks_lower[network] ~ '_mtu')) }}
          {%- endfor %}
          {% set min_viable_mtu = mtu_list | max %}
          network_config:
          - type: ovs_bridge
            name: {{ neutron_physical_bridge_name }}
            mtu: {{ min_viable_mtu }}
            use_dhcp: false
            dns_servers: {{ ctlplane_dns_nameservers }}
            domain: {{ dns_search_domains }}
            addresses:
            - ip_netmask: {{ ctlplane_ip }}/{{ ctlplane_subnet_cidr }}
            routes: {{ ctlplane_host_routes }}
            members:
            - type: interface
              name: nic1
              mtu: {{ min_viable_mtu }}
              # force the MAC address of the bridge to this interface
              primary: true
          {% for network in role_networks %}
            - type: vlan
              mtu: {{ lookup('vars', networks_lower[network] ~ '_mtu') }}
              vlan_id: {{ lookup('vars', networks_lower[network] ~ '_vlan_id') }}
              addresses:
              - ip_netmask:
                  {{ lookup('vars', networks_lower[network] ~ '_ip') }}/{{ lookup('vars', networks_lower[network] ~ '_cidr') }}
              routes: {{ lookup('vars', networks_lower[network] ~ '_host_routes') }}
          {% endfor %}
        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false
        edpm_nova_compute_container_image: '{{ registry_url }}/{{ image_prefix }}-nova-compute:{{
          image_tag }}'
        edpm_nova_libvirt_container_image: '{{ registry_url }}/{{ image_prefix }}-nova-libvirt:{{
          image_tag }}'
        edpm_ovn_controller_agent_image: '{{ registry_url }}/{{ image_prefix }}-ovn-controller:{{
          image_tag }}'
        edpm_ovn_metadata_agent_image: '{{ registry_url }}/{{ image_prefix }}-neutron-metadata-agent-ovn:{{
          image_tag }}'
        edpm_selinux_mode: enforcing
        edpm_sshd_allowed_ranges:
        - 192.168.122.0/24
        edpm_sshd_configure_firewall: true
        enable_debug: false
        external_cidr: "24"
        external_host_routes: []
        external_mtu: 1500
        external_vlan_id: 44
        gather_facts: false
        image_tag: current-podified
        image_prefix: openstack
        internal_api_cidr: "24"
        internal_api_host_routes: []
        internal_api_mtu: 1500
        internal_api_vlan_id: 20
        networks_lower:
          External: external
          InternalApi: internal_api
          Storage: storage
          Tenant: tenant
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: eth0
        registry_url: quay.io/podified-antelope-centos9
        role_networks:
        - InternalApi
        - Storage
        - Tenant
        service_net_map:
          nova_api_network: internal_api
          nova_libvirt_network: internal_api
        storage_cidr: "24"
        storage_host_routes: []
        storage_vlan_id: 21
        storage_mtu: 9000
        tenant_cidr: "24"
        tenant_host_routes: []
        tenant_mtu: 1500
        tenant_vlan_id: 22
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    # Create a secret called ceph-conf-files with the cephx key and
    # ceph.conf file and mount it so the ceph-client service can copy
    # those files to the EDPM nodes.
    extraMounts:
    - extraVolType: Logs
      mounts:
      - mountPath: /runner/artifacts
        name: ansible-logs
      volumes:
      - name: ansible-logs
        persistentVolumeClaim:
          claimName: ansible-ee-logs
    - extraVolType: Ceph
      mounts:
      - mountPath: /etc/ceph
        name: ceph
        readOnly: true
      volumes:
      - name: ceph
        projected:
          sources:
          - secret:
              name: ceph-conf-files
    managementNetwork: ctlplane
  nodes:
    edpm-compute-0:
      ansible:
        ansibleHost: 192.168.122.100
      hostName: edpm-compute-0
      networks:
      - defaultRoute: true
        fixedIP: 192.168.122.100
        name: CtlPlane
        subnetName: subnet1
      - name: InternalApi
        subnetName: subnet1
      - name: Storage
        subnetName: subnet1
      - name: Tenant
        subnetName: subnet1
    edpm-compute-1:
      ansible:
        ansibleHost: 192.168.122.101
      hostName: edpm-compute-1
      networks:
      - defaultRoute: true
        fixedIP: 192.168.122.101
        name: CtlPlane
        subnetName: subnet1
      - name: InternalApi
        subnetName: subnet1
      - name: Storage
        subnetName: subnet1
      - name: Tenant
        subnetName: subnet1
    edpm-compute-2:
      ansible:
        ansibleHost: 192.168.122.102
      hostName: edpm-compute-2
      networks:
      - defaultRoute: true
        fixedIP: 192.168.122.102
        name: CtlPlane
        subnetName: subnet1
      - name: InternalApi
        subnetName: subnet1
      - name: Storage
        subnetName: subnet1
      - name: Tenant
        subnetName: subnet1
  preProvisioned: true
  # Create a nova-custom-ceph service which uses a ConfigMap
  # containing libvirt overrides for Ceph RBD.
  services:
    - bootstrap
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - run-os
    - ceph-client
    - ovn
    - neutron-metadata
    - libvirt
    - nova-custom-ceph
