apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNode
metadata:
  name: edpm-compute-1
spec:
  role: edpm-compute
  hostName: edpm-compute-1
  ansibleHost: 192.168.122.101
  node:
    ansibleVars: |
      tenant_ip: 192.168.24.101
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
  deployStrategy:
    deploy: false
