apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlane
metadata:
  name: openstack-edpm
spec:
  deployStrategy:
      deploy: false
  nodes:
    edpm-compute-0:
      role: edpm-compute
      hostName: edpm-compute-0
      ansibleHost: 192.168.122.100
      node:
        ansibleVars: {}
        networks:
        - name: CtlPlane
          subnetName: subnet1
          defaultRoute: true
          fixedIP: 192.168.122.100
        - name: InternalApi
          subnetName: subnet1
        - name: Storage
          subnetName: subnet1
        - name: Tenant
          subnetName: subnet1
      deployStrategy:
        deploy: false
    edpm-compute-1:
      role: edpm-compute
      hostName: edpm-compute-1
      ansibleHost: 192.168.122.101
      node:
       ansibleVars: {}
       networks:
       - name: CtlPlane
         subnetName: subnet1
         defaultRoute: true
         fixedIP: 192.168.122.101
       - name: InternalApi
         subnetName: subnet1
       - name: Storage
         subnetName: subnet1
       - name: Tenant
         subnetName: subnet1
      deployStrategy:
        deploy: false
  roles:
    edpm-compute:
      env:
        - name: ANSIBLE_FORCE_COLOR
          value: "True"
        - name: ANSIBLE_ENABLE_TASK_DEBUGGER
          value: "True"
      preProvisioned: true
      services:
        - configure-network
        - validate-network
        - install-os
        - configure-os
        - run-os
        - ovn
      networkAttachments:
        - ctlplane
      nodeTemplate:
        # Defining the novaTemplate here means the nodes in this role are
        # computes
        nova: {}
        managementNetwork: ctlplane
        ansibleUser: root
        ansiblePort: 22
        ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
        ansibleVars:
          service_net_map:
            nova_api_network: internal_api
            nova_libvirt_network: internal_api

          # edpm_network_config
          # Default nic config template for a EDPM compute node
          # These vars are edpm_network_config role vars
          edpm_network_config_template: templates/single_nic_vlans/single_nic_vlans.j2
          edpm_network_config_hide_sensitive_logs: false
          #
          # These vars are for the network config templates themselves and are
          # considered EDPM network defaults.
          neutron_physical_bridge_name: br-ex
          neutron_public_interface_name: eth0
          role_networks:
          - InternalApi
          - Storage
          - Tenant
          networks_lower:
            External: external
            InternalApi: internal_api
            Storage: storage
            Tenant: tenant

          # edpm_nodes_validation
          edpm_nodes_validation_validate_controllers_icmp: false
          edpm_nodes_validation_validate_gateway_icmp: false

          edpm_ovn_metadata_agent_metadata_agent_DEFAULT_metadata_proxy_shared_secret: 12345678
          edpm_ovn_metadata_agent_DEFAULT_bind_host: 127.0.0.1
          edpm_chrony_ntp_servers:
          - clock.redhat.com
          - clock2.redhat.com
          registry_url: quay.io/podified-antelope-centos9
          image_tag: current-podified
          edpm_ovn_controller_agent_image: "{{ registry_url }}/openstack-ovn-controller:{{ image_tag }}"
          edpm_iscsid_image: "{{ registry_url }}/openstack-iscsid:{{ image_tag }}"
          edpm_logrotate_crond_image: "{{ registry_url }}/openstack-cron:{{ image_tag }}"
          edpm_nova_compute_container_image: "{{ registry_url }}/openstack-nova-compute:{{ image_tag }}"
          edpm_nova_libvirt_container_image: "{{ registry_url }}/openstack-nova-libvirt:{{ image_tag }}"
          edpm_ovn_metadata_agent_image: "{{ registry_url }}/openstack-neutron-metadata-agent-ovn:{{ image_tag }}"
          gather_facts: false
          enable_debug: false
          # edpm firewall, change the allowed CIDR if needed
          edpm_sshd_configure_firewall: true
          edpm_sshd_allowed_ranges: ['192.168.122.0/24']
          # SELinux module
          edpm_selinux_mode: enforcing
      deployStrategy:
        deploy: false
