---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlane
metadata:
  name: openstack-edpm
spec:
  deployStrategy:
      deploy: false
  nodes:
    edpm-compute-0:
      role: edpm-compute
      hostName: edpm-compute-0
      node:
        ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    edpm-compute-1:
      role: edpm-compute
      hostName: edpm-compute-1
      node:
        ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
  roles:
    edpm-compute:
      env:
        - name: ANSIBLE_FORCE_COLOR
          value: "True"
        - name: ANSIBLE_ENABLE_TASK_DEBUGGER
          value: "True"
        - name: ANSIBLE_VERBOSITY
          value: "2"
      baremetalSetTemplate:
        deploymentSSHSecret: dataplane-ansible-ssh-private-key-secret
        bmhLabelSelector:
          app: openstack
        ctlplaneInterface: enp1s0
        dnsSearchDomains:
          - osptest.openstack.org
      nodeTemplate:
        nova: {}
        networks:
        - name: CtlPlane
          subnetName: subnet1
          defaultRoute: true
        - name: InternalApi
          subnetName: subnet1
        - name: Storage
          subnetName: subnet1
        - name: Tenant
          subnetName: subnet1
        managementNetwork: CtlPlane
        ansibleUser: cloud-admin
        ansiblePort: 22
        ansibleVars:
          service_net_map:
            nova_api_network: internal_api
            nova_libvirt_network: internal_api
          edpm_chrony_ntp_servers:
            - 0.pool.ntp.org
            - 1.pool.ntp.org
          # edpm_network_config
          # Default nic config template for a EDPM compute node
          # These vars are edpm_network_config role vars
          edpm_network_config_template: templates/single_nic_vlans/single_nic_vlans.j2
          edpm_network_config_hide_sensitive_logs: false
          # These vars are for the network config templates themselves and are
          # considered EDPM network defaults.
          neutron_physical_bridge_name: br-ex
          neutron_public_interface_name: eth0
          role_networks:
          - InternalApi
          - Storage
          - Tenant
          networks_lower:
            External: external
            InternalApi: internal_api
            Storage: storage
            Tenant: tenant

          # edpm_nodes_validation
          edpm_nodes_validation_validate_controllers_icmp: false
          edpm_nodes_validation_validate_gateway_icmp: false

          edpm_ovn_metadata_agent_default_transport_url: rabbit://default_user@rabbitmq.openstack.svc:5672
          edpm_ovn_metadata_agent_metadata_agent_ovn_ovn_sb_connection: tcp:10.217.5.121:6642
          edpm_ovn_metadata_agent_metadata_agent_default_nova_metadata_host: 127.0.0.1
          edpm_ovn_metadata_agent_metadata_agent_default_metadata_proxy_shared_secret: 12345678
          edpm_ovn_metadata_agent_default_bind_host: 127.0.0.1
          dns_search_domains: []
          edpm_ovn_dbs:
          - 192.168.111.1

          registry_url: quay.io/podified-antelope-centos9
          image_tag: current-podified
          edpm_ovn_controller_agent_image: "{{ registry_url }}/openstack-ovn-controller:{{ image_tag }}"
          edpm_iscsid_image: "{{ registry_url }}/openstack-iscsid:{{ image_tag }}"
          edpm_logrotate_crond_image: "{{ registry_url }}/openstack-cron:{{ image_tag }}"
          edpm_nova_compute_container_image: "{{ registry_url }}/openstack-nova-compute:{{ image_tag }}"
          edpm_nova_libvirt_container_image: "{{ registry_url }}/openstack-nova-libvirt:{{ image_tag }}"
          edpm_ovn_metadata_agent_image: "{{ registry_url }}/openstack-neutron-metadata-agent-ovn:{{ image_tag }}"

          gather_facts: false
          enable_debug: false
          # edpm firewall, change the allowed CIDR if needed
          edpm_sshd_configure_firewall: true
          edpm_sshd_allowed_ranges: ['192.168.111.0/24']
          # SELinux module
          edpm_selinux_mode: enforcing
      deployStrategy:
        deploy: false
