---
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneNodeSet
metadata:
  name: openstack-edpm-custom-network
spec:
  env:
    - name: ANSIBLE_FORCE_COLOR
      value: "True"
    - name: ANSIBLE_ENABLE_TASK_DEBUGGER
      value: "True"
    - name: ANSIBLE_VERBOSITY
      value: 4
    - name: ANSIBLE_HOST_KEY_CHECKING
      value: false
  services:
    - download-cache
    - configure-network
    - validate-network
    - install-os
    - configure-os
    - run-os
    - ovn
    - libvirt
    - nova
  deployStrategy:
    deploy: false
  nodes:
    edpm-compute-0:
      hostName: edpm-compute-0
      ansible:
        ansibleHost: 192.168.1.5
        ansibleVars:
          ctlplane_ip: 192.168.1.5
          internal_api_ip: 172.17.0.101
          storage_ip: 172.18.0.101
          tenant_ip: 172.19.0.101
          external_ip: 172.20.12.76
          fqdn_internal_api: edpm-compute-1.example.com
          ansible_ssh_transfer_method: scp
  nodeTemplate:
    ansibleSSHPrivateKeySecret: dataplane-ansible-ssh-private-key-secret
    managementNetwork: ctlplane
    ansible:
      ansibleUser: cloud-admin
      ansiblePort: 22
      ansibleVars:
        # edpm_network_config
        # Default nic config template for a EDPM compute node
        # These vars are edpm_network_config role vars
        edpm_network_config_template: /runner/network/nic-config-template
        edpm_network_config_hide_sensitive_logs: false
        edpm_network_config_update: false
        #
        # These vars are for the network config templates themselves and are
        # considered EDPM network defaults.
        neutron_physical_bridge_name: br-ex
        neutron_public_interface_name: enp7s0
        ctlplane_mtu: 1500
        ctlplane_subnet_cidr: 24
        ctlplane_gateway_ip: 192.168.1.254
        ctlplane_host_routes:
        - ip_netmask: 0.0.0.0/0
          next_hop: 192.168.1.254
        external_mtu: 1500
        external_vlan_id: 4
        external_cidr: '24'
        external_host_routes: []
        internal_api_mtu: 1500
        internal_api_vlan_id: 20
        internal_api_cidr: '24'
        internal_api_host_routes: []
        storage_mtu: 1500
        storage_vlan_id: 21
        storage_cidr: '24'
        storage_host_routes: []
        tenant_mtu: 1500
        tenant_vlan_id: 22
        tenant_cidr: '24'
        tenant_host_routes: []
        role_networks:
        - InternalApi
        - Storage
        - Tenant
        - External
        networks_lower:
          External: external
          InternalApi: internal_api
          Storage: storage
          Tenant: tenant
        # edpm_nodes_validation
        edpm_nodes_validation_validate_controllers_icmp: false
        edpm_nodes_validation_validate_gateway_icmp: false
        ctlplane_dns_nameservers:
        - 192.168.1.254
        dns_search_domains: []
        edpm_ovn_dbs:
        - 192.168.24.1
        gather_facts: false
        enable_debug: false
        # edpm firewall, change the allowed CIDR if needed
        edpm_sshd_configure_firewall: true
        edpm_sshd_allowed_ranges: ['192.168.0.0/24', '172.20.0.0/16']
        # SELinux module
        edpm_selinux_mode: enforcing
    networkConfig:
      template: |
        ---
        network_config:
        - type: interface
          name: nic2
          mtu: 1500
          addresses:
            - ip_netmask:
                {{ ctlplane_ip }}/{{ ctlplane_subnet_cidr }}
        - type: ovs_bridge
          name: {{ neutron_physical_bridge_name }}
          mtu: 1500
          use_dhcp: false
          dns_servers: {{ ctlplane_dns_nameservers }}
          domain: []
          addresses:
          - ip_netmask: {{ lookup('vars', networks_lower["External"] ~ '_ip') }}/{{ lookup('vars', networks_lower["External"] ~ '_cidr') }}
          routes: [{'ip_netmask': '0.0.0.0/0', 'next_hop': '192.168.1.254'}]
          members:
          - type: interface
            name: nic1
            mtu: 1500
            # force the MAC address of the bridge to this interface
            primary: true
          - type: vlan
            mtu: 1500
            vlan_id: 20
            addresses:
            - ip_netmask:
                172.17.0.101/24
            routes: []
          - type: vlan
            mtu: 1500
            vlan_id: 25
            addresses:
            - ip_netmask:
                172.18.0.101/24
            routes: []
          - type: vlan
            mtu: 1500
            vlan_id: 22
            addresses:
            - ip_netmask:
                172.19.0.101/24
            routes: []
