## Append samples you want in your CSV to this file as resources ##
resources:
- dataplane_v1beta1_openstackdataplane.yaml
- dataplane_v1beta1_openstackdataplanerole.yaml
- dataplane_v1beta1_openstackdataplanenode.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
