---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: openstackdataplanenodes.dataplane.openstack.org
spec:
  group: dataplane.openstack.org
  names:
    kind: OpenStackDataPlaneNode
    listKind: OpenStackDataPlaneNodeList
    plural: openstackdataplanenodes
    singular: openstackdataplanenode
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status
      jsonPath: .status.conditions[0].status
      name: Status
      type: string
    - description: Message
      jsonPath: .status.conditions[0].message
      name: Message
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: OpenStackDataPlaneNode is the Schema for the openstackdataplanenodes
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenStackDataPlaneNodeSpec defines the desired state of OpenStackDataPlaneNode
            properties:
              ansibleHost:
                description: AnsibleHost SSH host for Ansible connection
                type: string
              deploy:
                default: true
                description: Deploy boolean to trigger ansible execution
                type: boolean
              hostName:
                description: HostName - node name
                type: string
              networkAttachments:
                description: NetworkAttachments is a list of NetworkAttachment resource
                  names to pass to the ansibleee resource which allows to connect
                  the ansibleee runner to the given network
                items:
                  type: string
                type: array
              node:
                description: Node - node attributes specific to this node
                properties:
                  ansiblePort:
                    description: AnsiblePort SSH port for Ansible connection
                    type: integer
                  ansibleSSHPrivateKeySecret:
                    description: 'AnsibleSSHPrivateKeySecret Private SSH Key secret
                      containing private SSH key for connecting to node. Must be of
                      the form: Secret.data.ssh-privatekey: <base64 encoded private
                      key contents> https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets'
                    type: string
                  ansibleUser:
                    description: AnsibleUser SSH user for Ansible connection
                    type: string
                  ansibleVars:
                    description: AnsibleVars for configuring ansible
                    type: string
                  managed:
                    description: Managed - Whether the node is actually provisioned
                      (True) or should be treated as preprovisioned (False)
                    type: boolean
                  managementNetwork:
                    description: ManagementNetwork - Name of network to use for management
                      (SSH/Ansible)
                    type: string
                  networkConfig:
                    description: NetworkConfig - Network configuration details. Contains
                      os-net-config related properties.
                    properties:
                      template:
                        default: templates/net_config_bridge.j2
                        description: Template - ansible j2 nic config template to
                          use when applying node network configuration
                        type: string
                    type: object
                  networks:
                    description: Networks - Instance networks
                    items:
                      description: NetworksSection is a specification of the network
                        attributes
                      properties:
                        fixedIP:
                          description: FixedIP - Specific IP address to use for this
                            network
                          type: string
                        network:
                          description: Network - Network name to configure
                          type: string
                      type: object
                    type: array
                required:
                - ansibleSSHPrivateKeySecret
                type: object
              nodeFrom:
                description: NodeFrom - Existing node name to reference. Can only
                  be used if Node is empty.
                type: string
              openStackAnsibleEERunnerImage:
                default: quay.io/openstack-k8s-operators/openstack-ansibleee-runner:latest
                description: OpenStackAnsibleEERunnerImage image to use as the ansibleEE
                  runner image
                type: string
              role:
                description: Role - role name for this node
                type: string
            required:
            - deploy
            type: object
          status:
            description: OpenStackDataPlaneNodeStatus defines the observed state of
              OpenStackDataPlaneNode
            properties:
              conditions:
                description: Conditions
                items:
                  description: Condition defines an observation of a API resource
                    operational state.
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.
                        If that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase.
                      type: string
                    severity:
                      description: Severity provides a classification of Reason code,
                        so the current situation is immediately understandable and
                        could act accordingly. It is meant for situations where Status=False
                        and it should be indicated if it is just informational, warning
                        (next reconciliation might fix it) or an error (e.g. DB create
                        issue and no actions to automatically resolve the issue can/should
                        be done). For conditions where Status=Unknown or Status=True
                        the Severity should be SeverityNone.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase.
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              deployed:
                description: Deployed
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
