---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: openstackdataplanes.dataplane.openstack.org
spec:
  group: dataplane.openstack.org
  names:
    kind: OpenStackDataPlane
    listKind: OpenStackDataPlaneList
    plural: openstackdataplanes
    singular: openstackdataplane
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        description: OpenStackDataPlane is the Schema for the openstackdataplanes
          API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OpenStackDataPlaneSpec defines the desired state of OpenStackDataPlane
            properties:
              dataPlaneRoles:
                description: DataPlaneRoles - List of roles
                items:
                  description: OpenStackDataPlaneRoleSpec defines the desired state
                    of OpenStackDataPlaneRole
                  properties:
                    dataPlaneNodes:
                      description: DataPlaneNodes - List of nodes
                      items:
                        description: OpenStackDataPlaneNodeSpec defines the desired
                          state of OpenStackDataPlaneNode
                        properties:
                          ansibleHost:
                            description: AnsibleHost SSH host for Ansible connection
                            type: string
                          deploy:
                            default: true
                            description: Deploy boolean to trigger ansible execution
                            type: boolean
                          hostName:
                            description: HostName - node name
                            type: string
                          node:
                            description: Node - node attributes specific to this node
                            properties:
                              ansiblePort:
                                description: AnsiblePort SSH port for Ansible connection
                                type: integer
                              ansibleSSHPrivateKeySecret:
                                description: 'AnsibleSSHPrivateKeySecret Private SSH
                                  Key secret containing private SSH key for connecting
                                  to node. Must be of the form: Secret.data.ssh-privatekey:
                                  <base64 encoded private key contents> https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets'
                                type: string
                              ansibleUser:
                                description: AnsibleUser SSH user for Ansible connection
                                type: string
                              ansibleVars:
                                description: AnsibleVars for configuring ansible
                                type: string
                              managed:
                                description: Managed - Whether the node is actually
                                  provisioned (True) or should be treated as preprovisioned
                                  (False)
                                type: boolean
                              managementNetwork:
                                description: ManagementNetwork - Name of network to
                                  use for management (SSH/Ansible)
                                type: string
                              networkConfig:
                                description: NetworkConfig - Network configuration
                                  details. Contains os-net-config related properties.
                                properties:
                                  template:
                                    default: templates/net_config_bridge.j2
                                    description: Template - ansible j2 nic config
                                      template to use when applying node network configuration
                                    type: string
                                type: object
                              networks:
                                description: Networks - Instance networks
                                items:
                                  description: NetworksSection is a specification
                                    of the network attributes
                                  properties:
                                    fixedIP:
                                      description: FixedIP - Specific IP address to
                                        use for this network
                                      type: string
                                    network:
                                      description: Network - Network name to configure
                                      type: string
                                  type: object
                                type: array
                            required:
                            - ansibleSSHPrivateKeySecret
                            type: object
                          nodeFrom:
                            description: NodeFrom - Existing node name to reference.
                              Can only be used if Node is empty.
                            type: string
                          role:
                            description: Role - role name for this node
                            type: string
                        required:
                        - deploy
                        type: object
                      type: array
                    nodeTemplate:
                      description: NodeTemplate - node attributes specific to this
                        roles
                      properties:
                        ansiblePort:
                          description: AnsiblePort SSH port for Ansible connection
                          type: integer
                        ansibleSSHPrivateKeySecret:
                          description: 'AnsibleSSHPrivateKeySecret Private SSH Key
                            secret containing private SSH key for connecting to node.
                            Must be of the form: Secret.data.ssh-privatekey: <base64
                            encoded private key contents> https://kubernetes.io/docs/concepts/configuration/secret/#ssh-authentication-secrets'
                          type: string
                        ansibleUser:
                          description: AnsibleUser SSH user for Ansible connection
                          type: string
                        ansibleVars:
                          description: AnsibleVars for configuring ansible
                          type: string
                        managed:
                          description: Managed - Whether the node is actually provisioned
                            (True) or should be treated as preprovisioned (False)
                          type: boolean
                        managementNetwork:
                          description: ManagementNetwork - Name of network to use
                            for management (SSH/Ansible)
                          type: string
                        networkConfig:
                          description: NetworkConfig - Network configuration details.
                            Contains os-net-config related properties.
                          properties:
                            template:
                              default: templates/net_config_bridge.j2
                              description: Template - ansible j2 nic config template
                                to use when applying node network configuration
                              type: string
                          type: object
                        networks:
                          description: Networks - Instance networks
                          items:
                            description: NetworksSection is a specification of the
                              network attributes
                            properties:
                              fixedIP:
                                description: FixedIP - Specific IP address to use
                                  for this network
                                type: string
                              network:
                                description: Network - Network name to configure
                                type: string
                            type: object
                          type: array
                      required:
                      - ansibleSSHPrivateKeySecret
                      type: object
                  type: object
                type: array
            type: object
          status:
            description: OpenStackDataPlaneStatus defines the observed state of OpenStackDataPlane
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
